name: Deploy Theme to Shopify (UJ Store)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout UJ Store Repo
        uses: actions/checkout@v4

      - name: Initialize and Update Submodule (moonbase)
        run: |
          git submodule init
          git submodule update --remote --merge

      - name: Merge Base Theme with UJ Customizations
        run: |
          mkdir merged_theme
          cp -R moonbase/* merged_theme/
          cp -R sections/* merged_theme/sections/
          cp -R assets/* merged_theme/assets/
          cp -R config/* merged_theme/config/
          # Copy over other store-specific customizations if needed

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Deploy to Shopify
        run: |
          shopify theme push --path=merged_theme --store=${{ secrets.SHOPIFY_STORE_URL }} --password=${{ secrets.SHOPIFY_ACCESS_TOKEN }}

